# Generated by Django 3.2.4 on 2021-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(help_text='Language of the book', max_length=50, null=True),
        ),
    ]
